name: Arcaflow CI Workflow
on:
  push:
    branches:
      - "**"
  release:
    types:
      - published
jobs:
  docsgen:
    uses: arcalot/arcaflow-docsgen/.github/workflows/reusable_workflow.yaml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      plugin_path: "arcaflow_plugin_getting_started_example/getting_started_example_plugin.py"
